from pathlib import Path
import json,xml.etree.ElementTree as E
p=Path('app/page.tsx');s=p.read_text()
def change(a,b):
 global s
 assert a in s,a[:100]
 s=s.replace(a,b)
change('style:string;specs:', 'style:string;room?:string;specs:')
change(" const [products,setProducts]", " const [mega,setMega]=useState(false),[filtersOpen,setFiltersOpen]=useState(false),[color,setColor]=useState('all'),[style,setStyle]=useState('all'),[room,setRoom]=useState('all'),[diameter,setDiameter]=useState(''),[power,setPower]=useState(''),[lightOn,setLightOn]=useState(false),[zoom,setZoom]=useState(false);\n const [products,setProducts]")
change("function nav(v:string){setView(v);setMenu(false);", "function nav(v:string){setView(v);setMenu(false);setMega(false);")
change("function catalog(c='all'){setCategory(c);setQuery('');setLimit(24);nav('catalog')}","function resetFilters(){setCategory('all');setBrand('all');setSocket('all');setColor('all');setStyle('all');setRoom('all');setDiameter('');setPower('');setMax('');setQuery('')}\n function catalog(c='all'){resetFilters();setCategory(c);setLimit(24);nav('catalog')}")
change("&&(socket==='all'||p.socket===socket)","&&(socket==='all'||p.socket===socket)&&(color==='all'||p.color===color)&&(style==='all'||p.style===style)&&(room==='all'||(p.room||'').split(';').map(x=>x.trim()).includes(room))&&(!diameter||(Number(p.specs['Светильник Диаметр, мм'])>0&&Number(p.specs['Светильник Диаметр, мм'])<=Number(diameter)))&&(!power||(Number(p.specs['Общая мощность, Вт'])>0&&Number(p.specs['Общая мощность, Вт'])<=Number(power)))")
change('[products,view,fav,category,brand,socket,max,query,sort]','[products,view,fav,category,brand,socket,max,query,sort,color,style,room,diameter,power]')
change('function open(p:Product){setPhoto(0);setSelected(p)}','function open(p:Product){setPhoto(0);setLightOn(night);setSelected(p)}')
change("onClick={()=>v==='catalog'?catalog():nav(v)}", "onClick={()=>v==='catalog'?setMega(true):nav(v)}")
change("onClick={()=>nav(v)}>{t}</button>)}</div>}","onClick={()=>v==='catalog'?(setMenu(false),setMega(true)):nav(v)}>{t}</button>)}</div>}")
change(' const navItems=', ''' useEffect(()=>{const nodes=document.querySelectorAll('.section-heading,.category-card,.showroom-intro,.night-banner');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});nodes.forEach(n=>{n.classList.add('reveal');observer.observe(n)});return()=>{observer.disconnect();nodes.forEach(n=>n.classList.remove('reveal'))}},[view,loading]);
 useEffect(()=>{setLimit(24)},[category,brand,socket,max,query,sort,color,style,room,diameter,power]);
 const filterChips:[string,()=>void][]=[...(category!=='all'?[[category,()=>setCategory('all')] as [string,()=>void]]:[]),...(brand!=='all'?[[brand,()=>setBrand('all')] as [string,()=>void]]:[]),...(socket!=='all'?[[socket,()=>setSocket('all')] as [string,()=>void]]:[]),...(color!=='all'?[[color,()=>setColor('all')] as [string,()=>void]]:[]),...(style!=='all'?[[style,()=>setStyle('all')] as [string,()=>void]]:[]),...(room!=='all'?[[room,()=>setRoom('all')] as [string,()=>void]]:[]),...(max?[[`До ${money(Number(max))}`,()=>setMax('')] as [string,()=>void]]:[]),...(diameter?[[`Диаметр до ${diameter} мм`,()=>setDiameter('')] as [string,()=>void]]:[]),...(power?[[`До ${power} Вт`,()=>setPower('')] as [string,()=>void]]:[])];
 const navItems=''')
# Extract existing desktop filter controls for shared mobile sheet.
start=s.index('<aside><h3>');end=s.index('</aside>',start)+len('</aside>')
body=s[start+len('<aside>'):end-len('</aside>')]
extra='''<label>Цвет<Choice value={color} onChange={setColor} items={ [['all','Любой цвет'],...[...new Set(visible.map(p=>p.color))].filter(v=>v&&v!=='-'&&v!=='_').sort().map(v=>[v,v] as [string,string])]}/></label><label>Стиль<Choice value={style} onChange={setStyle} items={ [['all','Любой стиль'],...[...new Set(visible.map(p=>p.style))].filter(v=>v&&v!=='-'&&v!=='_').sort().map(v=>[v,v] as [string,string])]}/></label><label>Помещение<Choice value={room} onChange={setRoom} items={ [['all','Любое помещение'],...[...new Set(visible.flatMap(p=>(p.room||'').split(';').map(v=>v.trim())))].filter(v=>v&&v!=='-'&&v!=='_').sort().map(v=>[v,v] as [string,string])]}/></label><label>Диаметр до, мм<input type="number" min="1" value={diameter} onChange={e=>setDiameter(e.target.value)} placeholder="Любой"/></label><label>Мощность до, Вт<input type="number" min="1" value={power} onChange={e=>setPower(e.target.value)} placeholder="Любая"/></label>'''
body=body.replace('<button className="text-button"',extra+'<button className="text-button"',1)
body=body.replace("onClick={()=>{setCategory('all');setBrand('all');setSocket('all');setMax('');setQuery('')}}",'onClick={resetFilters}')
s=s[:start]+'<aside className="desktop-filters">{filterControls()}</aside>'+s[end:]
change(' const navItems=', ' function filterControls(){return <>'+body+'</>}\n const navItems=')
change('<div className="catalog-layout">','<button className="outline mobile-filters" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={18}/> Фильтры {filterChips.length>0&&`(${filterChips.length})`}</button><div className="filter-chips">{filterChips.map(([t,clear])=><button key={t} onClick={clear}>{t}<X size={14}/></button>)}{filterChips.length>1&&<button onClick={resetFilters}>Сбросить всё</button>}</div><div className="catalog-layout">')
change(' <footer>', ''' <Dialog open={mega} onOpenChange={setMega}><DialogContent className="mega-dialog"><DialogTitle>Найдите свой свет</DialogTitle><DialogDescription>Выберите категорию или откройте весь каталог.</DialogDescription><div className="mega-grid">{['Люстр','Подвес','Бра','Трек','Торшер','Настольн','Уличн','Спот'].map((stem,i)=>{const p=visible.find(p=>p.category.toLowerCase().includes(stem.toLowerCase()));const labels=['Люстры','Подвесы','Бра','Трековые системы','Торшеры','Настольные лампы','Уличное освещение','Споты'];return p?<button key={stem} onClick={()=>catalog(p.category)}><img src={p.pictures[0]} alt="" loading="lazy"/><span>{labels[i]}<Plus size={16}/></span></button>:null})}</div><div className="mega-bottom"><button className="primary" onClick={()=>catalog()}>Открыть весь каталог</button><span>Найдём свет для вашей идеи · <a href="tel:+79259088988">+7 (925) 908-89-88</a></span></div></DialogContent></Dialog>
 <Sheet open={filtersOpen} onOpenChange={setFiltersOpen}><SheetContent side="left" className="filter-sheet"><SheetTitle>Подбор освещения</SheetTitle><SheetDescription>Укажите подходящие параметры.</SheetDescription>{filterControls()}<button className="primary apply-filters" onClick={()=>setFiltersOpen(false)}>Показать модели: {filtered.length}</button></SheetContent></Sheet>
 <footer>''')
change('<div className="detail-photos"><img className="detail-main"', '<div className="detail-photos"><button className="zoom-photo" aria-label="Увеличить фотографию" onClick={()=>setZoom(true)}><img className="detail-main"')
change('src={photo===0&&night&&selected.lit.startsWith(\'http\')?selected.lit:selected.pictures[photo]}','src={photo===0&&selected.unlit.startsWith("http")&&selected.lit.startsWith("http")?(lightOn?selected.lit:selected.unlit):selected.pictures[photo]}')
change('alt={title(selected)}/><div className="thumbnails">','alt={title(selected)}/><span>Увеличить фото <Plus size={16}/></span></button>{selected.unlit.startsWith("http")&&selected.lit.startsWith("http")&&<label className="light-toggle"><Sun size={18}/><span>Свет {lightOn?"включён":"выключен"}</span><Switch checked={lightOn} onCheckedChange={v=>{setLightOn(v);setPhoto(0)}} aria-label="Включить свет на фото"/></label>}<div className="thumbnails">')
change('<h3>Характеристики</h3>', '<div className="key-specs">{["Светильник Диаметр, мм","Светильник Высота, мм","Тип цоколя лампы","Общая мощность, Вт"].filter(k=>selected.specs[k]).map(k=><div key={k}><small>{k.replace("Светильник ","")}</small><strong>{selected.specs[k]}</strong></div>)}</div><h3>Характеристики</h3>')
change(' <Dialog open={gallery!==null}', ''' <Dialog open={zoom} onOpenChange={setZoom}><DialogContent className="zoom-dialog"><DialogTitle>{selected?title(selected):'Фото светильника'}</DialogTitle><DialogDescription>Фотография поставщика</DialogDescription>{selected&&<img src={photo===0&&selected.unlit.startsWith('http')&&selected.lit.startsWith('http')?(lightOn?selected.lit:selected.unlit):selected.pictures[photo]} alt={title(selected)}/>}</DialogContent></Dialog>
 <Dialog open={gallery!==null}''')
change('</label><p>{delivery===\'pickup\'', '''</label><div className="order-summary"><div><span>Товары</span><strong>{money(total)}</strong></div><div><span>Доставка</span><strong>{delivery==='pickup'?'Бесплатно':delivery==='russia'?'По тарифу ТК':total>30000?'Бесплатно*':'2 000–3 000 ₽*'}</strong></div><div><span>{delivery==='pickup'?'Оплата в салоне':'Предоплата за товары'}</span><strong>{money(delivery==='moscow'?total*.5:total)}</strong></div>{delivery==='moscow'&&<div><span>За товары при получении</span><strong>{money(total*.5)}</strong></div>}</div>{delivery==='moscow'&&<div className="shipping-progress"><span>{total>30000?'Для заказа доступна бесплатная доставка*':`До бесплатной доставки — ${money(Math.max(0,30001-total))}`}</span><div><i style={{width:Math.min(100,total/30001*100)+'%'}}/></div><small>* Условия для крупногабаритных товаров уточняются.</small></div>}<p>{delivery==='pickup\' ''')
# remove accidental whitespace inside replacement expression if any
s=s.replace("delivery==='pickup' ?", "delivery==='pickup'?")
p.write_text(s)
# Enrich only public product metadata from the same approved snapshot.
data=json.loads(Path('public/catalog.json').read_text())
root=E.parse('../upload/stocks.yml').getroot()
rooms={o.get('id'):next((x.text or '' for x in o.findall('param') if x.get('name')=='Тип светильника_По помещению'),'') for o in root.findall('.//offer')}
for item in data['items']:item['room']=rooms.get(item['id'],'')
Path('public/catalog.json').write_text(json.dumps(data,ensure_ascii=False,separators=(',',':')))
print('Updated navigation, filters, detail view, cart and room metadata')
